[build]
  command = "npm run build"
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "@netlify/plugin-image-optim"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/iphone_images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/opengraph-image.png"
  [headers.values]
    Link = "</opengraph-image.png>; rel=preload; as=image"

[context.production.environment]
  NODE_ENV = "production"

[build.processing]
  css = false # Slå Netlify asset bundling fra for CSS