// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kzvxlkxjmdzodsxotoya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6dnhsa3hqbWR6b2RzeG90b3lhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MDg5OTMsImV4cCI6MjA3MTA4NDk5M30.WOma97Vdo6OGRXFA99I66HIC_q7UTyDFj47G891dRkw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});